### ISSUE TITLE
AdMob verifier-keys cache

### ISSUE THREAD

**Issue by peterkimga** [CasperLaiTW/laravel-admob-ssv#1]
Hi

Your class looks promising and I'm happy that I found it. 

I was just wondering can you implement a cache pool to it like "cache/filesystem-adapter"

I was thinking about something that can be used like that:

https://github.com/googleapis/google-api-php-client#caching

So the keys can be cached like the docs suggest they should be for 24h.

Or suggest how to add cache with your package.

Thanks
Peter

**Comment by CasperLaiTW** [comment]
it's good idea, I will try to store key to laravel cache. 

and should be need some config for enable / disable cache and how long to cache.

**Comment by peterkimga** [comment]
I think assigning this to any cache pool would be nice. 

Check the Google API PHP class that I attached.

They have any poll as an option to store.

Google also has keys valid for 24H so the pool will detect how long are valid and call for a new one once expired.

I will use your class not with Laravel but with Slim Framework, so that kind of any pool solution sounds better for me :) 

But also It can be used by anyone anyway also in Laravel.

BTW can you remove my nick from your post? I forgot this is my work GitHub :/

**Comment by CasperLaiTW** [comment]
well, I removed the tag. 

and I read your link, I will try to add PSR-6 compatible library for cache, I think laravel support it too. 

I will do some public method for you to assign cache driver to PublicKey class. so you can use in any project with other framework

also for free to PR, if you have some good idea.

**Comment by peterkimga** [comment]
Unfortunately, I  would if I knew how.

Luckily I can somehow use it and know what the possibilities are.

I can suggest and test it after no problem.

I think this will be a great addition to your packege. I would definitely use it.

Will try to connect your package with SlimFramework in the upcoming days. will let you know.

And If you add this will add it as well and also let you know 👍

**Comment by CasperLaiTW** [comment]
Easy, I will do cache in my free time.

Just for free to contribute. 

Have a nice day!

**Comment by peterkimga** [comment]
Hi again.

If this will not be all if you expose a way to pass a cache plugin to your constructor?

![image](https://user-images.githubusercontent.com/57945998/104000234-da565500-5195-11eb-954e-60ddc14dc8f4.png)

https://guzzle3.readthedocs.io/plugins/cache-plugin.html

I started to read this. This plugin will automatically handle expiry dates from the header.

So exposing a way to add cache compatible with Guzzle, it's all that you need to add.

**Comment by CasperLaiTW** [comment]
Hi I found a middleware for caching

how do you think about this one

https://github.com/Kevinrob/guzzle-cache-middleware

**Comment by peterkimga** [comment]
I actually use this one at the moment:

https://github.com/Kevinrob/guzzle-cache-middleware#flysystem

League\Flysystem\Adapter\Local

So I will say it's a go.

But check the url that I send you.

You can expose cache to guzzle and pass whatever you like. So the user of your package can implement his own if he's using one already.

If you going to add yours inside your package it will use it always and I will be forced to install it if I do not have it but I might have a different one. You can always add a standard one It's up to the User to decide.

I think you should just expose like an object parameter to your constructor with a cache option like so:

```
use Cache\Adapter\Filesystem\FilesystemCachePool;
use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;

$filesystemAdapter = new Local('cache_path');
$filesystem = new Filesystem($filesystemAdapter);
$cache = new FilesystemCachePool($filesystem);

$adMob = new AdMob($request, {
	cache:  $cache
});
```

and in your class PublicKey.php you should use it if its passed on:

```
public function __construct($id = null, &options = {})
    {
        if ($id) {
            $this->setKeyId($id);
        }

       if(isset(&options->cache)) {
            $this->cache = $options->cache
       }

        $this->fetchPublicKeys();
    }

```

and after

```

public function fetchPublicKeys()
    {
        $client = new Client();
        if(isset($this->cache)) {
            $client->addSubscriber($this->cache);
        }
        $response = $client->request('GET', $this->publicKeyUrl);

        return $this->keyMap = Json::decode($response->getBody()->getContents(), true);
    }

```

or something along those lines so it will work LOL :)

**Comment by peterkimga** [comment]
Middleware will be in adition. Use something that is already there.

**Comment by CasperLaiTW** [comment]
Hi, I made some code for cache. see if can you test in your local.

if all working and good for you, I will merge it

https://github.com/CasperLaiTW/laravel-admob-ssv/pull/2

**Comment by CasperLaiTW** [comment]
If you use `Admob` class, you can overwrite the `configureCache` if you need to use other cache driver.

if you didn't use Admob, you do some code by yourself, the cache driver register like this.

you can read https://github.com/CasperLaiTW/laravel-admob-ssv/blob/support-cache/src/AdMob.php#L70-L81

```
PublicKey::cacheThrough(function () {
            return new CacheMiddleware(
                new PrivateCacheStrategy(
                    new LaravelCacheStorage(
                        Cache::store()
                    )
                )
            );
        });
```

**Comment by peterkimga** [comment]
I left you some comments.

The Middleware will have a sense if you would put it outside your class not in it.

I do not think that adding an extra package and all of that is better than just exposing the cache configuration option.

It's almost everything ready In my previous comment.

you can after add your suggested cache configuration in the readme but you're not forcing anybody to use exactly this one just for the SSV. 

You have to get that your class should be small and work as a part of somebody's bigger project. Not be a project of its own.

I will test your class in a weekend and maybe do a PR of what I was thinking. I looked at it and I think I can do it 👍  And then we compare. What do you say to that?

I do not want to mess your project up but I see some points that are just not useful for me :)

**Comment by CasperLaiTW** [comment]
Thank you. 

I just tried to make it easily. So learned some code from laravel. 

And I think the static callable variable it's good idea for everyone if you want to customize. 

https://jetstream.laravel.com/1.x/features/authentication.html#customizing-user-authentication

And Admob class depends on laravel, there are some laravel class support it, the config will be a good option, but if you use laravel, I don't think you will switch cache driver. And if go people used laravel framework, and even want to switch cache driver, they can just extend Admob or call `PublicKey:: cacheThrough` for switch their cache driver

And if you use non-laravel framework, you should just use `PublicKey` and `Signature` class and make your `Admob` class. So config will not help you to setup in non-laravel framework.

And actually the package just for Admob SSV, and nothing more features.

**Comment by peterkimga** [comment]
Yes and No :)

Also Laravel packeges can be imported int other frameworks :)

So I use SlimFramework but got Eloquent Implementation which is a part of Laravel :)

Laravel it' a big mix of packeges that just work together but they can also be split apart and work with other frameworks :) I see you ware not fully aware of it :)

So this Auth class of Laravel I did not want to use in my App. I do not want to store user data and logins so I went with Google auth and created my own Middleware.

I wanted to have Easy DB access so I added Laravel Eloquent.

So I add the packages that I need.

Cause, let's be honest. Laravel is awesome, but also awesome big and heavy. I do not need anything.

Your class can be added, part of something else. If you just do not tie it too much whit packages that it depends on.

So this is what I try to tell you. Your package can be used in any PHP project. Not only Laravel. Let's make this happen :)

Now what you're missing its Guzzle compatible cache pool. That's it. You can connect any of them. So if your project (like mine) already has one I will like to just connect it, not have another one. 

Your solution ties me to Laravel that I do not have. And make the package bigger for no reason. And like you said I can make a small PR that will have this. I think middleware is a little too over the top, for what needs to be done in this case. I will use this middleware if I will like part of my requests to be cached and I do not have any cache yet. I learned myself that there is no reason to overcomplicate things and If devs at google decided that this is how we will implement the cache they did all the research and that's the best solution they came up with. I will do the same in my project. Cause there can be 1000 solutions out there. Let's hit most of them.

**Comment by CasperLaiTW** [comment]
I got bit confused.

My new update, I didn't force you to used my cache solution. 

And `Admob` class just like a service to easy validate for some people. 

But all base code that `PublicKey` and `Signature` all are public, so you can register your cache driver or disable cache if you don't need. 

Even you used `Admob` class, you can extend it and overwrite cache configure method too or call `PublicKey::cacheThrough` after create `Admob`. Also can switch cache driver

And if you don't want to use cache, you can just return empty array in cacheThrough callback method. 

In my concept, I think you can do disable cache, switch cache to any one you have, or nothing to do in default.

And I like your cache idea for get key, it's good, no reason to get the key from google every time. So I want to improved it in default.

**Comment by CasperLaiTW** [comment]
So according your post, I code some example to you.

After you created `PublicKey` or `Admob`, you can just add this code after them to switch driver

```php
PublicKey::cacheThrough(function () {
            return new CacheMiddleware(
                new PrivateCacheStrategy(
                    new FlysystemStorage(
                        new Local('/path/to/cache')
                    )
                )
             );
        });
```

if you use `Admob`, just create your own class and extends `Admob` then overwrite `configureCache` method to above code. I think its will switch to your cache driver.

so I'm not sure about my package force the laravel cache driver. you still can use one you have.

**Comment by peterkimga** [comment]
I'm looking at your class and decided to redo it again removing all "illuminate" classes using your code as a base.

Your class is connected verry much with Laravel. Im changing it to work with Psr request (I do not remember if Laravel use it internally).

But I ended up using additionally only: EllipticCurve\Ecdsa.

The rest was removed and replaced with default PHP methods that are doing the same thing. 

It's working.

As a note, you can remove completely this package: "Eastwest\Json\Json"

and remove line: 67, from: "src/PublicKey.php":

```
        return $this->keyMap = Json::decode($response->getBody()->getContents(), true);
```

with this:

```
        return $this->keyMap = json_decode($response->getBody()->getContents(), true);
```

No need to overblow the package with dependencies.

**Comment by CasperLaiTW** [comment]
I'm sorry. I built it for Laravel, for my project. And my all projects only work with Laravel, so if you want to removed some code, you can fork and publish your library.

I don't want to change any code except we discussed about cache.

My project is open source, you can copy and do anything you want 😀 

Thank you.

**Comment by peterkimga** [comment]
Yes exactly. The name says it as well 👍 

I got a different mindset even when coding something for a direct connection. This package above is not needed. I do not know if it's a part of Laravel but can be easily removed.

As a note. I moved all Illumination requests to Psr requests. And replaced all validations with pure PHP left with just this class: EllipticCurve\Ecdsa. And it works fine.

You are right with the cache. I also used it as well.

I noticed something with the Admob keys. They do not have an expiration date in the future. So if you do not use GreeedyCacheStrategy with TTL set up for a specific time (AdMob recommends 24 hours but I set up 12) then the cache is not used only every time created again. I started with PrivateCacheStrategy and it was not getting the refresh date from the headers. I checked the headers on the key JSON file and then I noticed it. Then read the docs and that came out:

https://developers.google.com/admob/android/rewarded-video-ssv#faq

topic: How frequently are the public keys provided by the AdMob key server rotated?

**Comment by CasperLaiTW** [comment]
HI, I tested with middleware, the middleware said the request HIT with cache.

so I think it's working. should we use Greedy Cache? and manage the TTL by user?

**Comment by peterkimga** [comment]
Yes. This is what I did I used Greedy and set TTL for 12 hours.

Set yourself with a postman URL, and after once call turn off the internet connection and try again. If it works is will validate if it's not using the cache.

Greedy works for me.

**Comment by CasperLaiTW** [comment]
Hi,

the `PrivateCacheStrategy` cache working fine to me

I think if you want to switch to Greedy. you can call the method to switch.

I will merge current version and add tag today.

cheers

**Comment by peterkimga** [comment]
Seriously?

Check its creating cache file but is creating it over and over again each time. Add it temporarily to git and check if it's not changing every time it makes a request. For me, it did Private and public. cause the headers on ADMOB have "expired now" and they are rotating randomly.

**Comment by CasperLaiTW** [comment]
Hello

I switched to Greedy Cache now.

Just checked the json key url, the response header didn't have cache values.

**Comment by CasperLaiTW** [comment]
Bump `v1.1.0` now
