### ISSUE TITLE
Please, Can provide sample for response data of callback

### ISSUE THREAD

**Issue by mahmoudhaggag641** [CasperLaiTW/laravel-admob-ssv#3]
Please, Can provide sample for response data of callback to confirm some business logic

**Comment by CasperLaiTW** [comment]
Hi, @MahmoudSaidHaggag 

You have to check document

https://developers.google.com/admob/android/ssv#get_content_to_be_verified

the callback content is always different in each request, but query params all as same in document

<img width="938" alt="截圖 2022-02-26 下午8 32 16" src="https://user-images.githubusercontent.com/5094008/155843273-f174a4bf-5f86-4fae-b71f-5c94bf1a07db.png">

**Comment by mahmoudhaggag641** [comment]
Thank you @CasperLaiTW , this is wonderful

**Comment by CasperLaiTW** [comment]
Closed, if you have another issues, just open new one for free :)
